---
id: HiroshimaGit201306
base_name: think-about-bare
tags: []
presentation_date: 2013/06/01
version: 2013.06.01
licenses: []
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
author:
  markup_language: :markdown
  name: ! '@ryosms'
  email: ryo.sms@gmail.com
  rubygems_user: 
  slideshare_user: 
  speaker_deck_user: 
